/* tslint:disable */
/* eslint-disable */
/**
 * Chat API
 * WebSocket chat service with anonymous pairing, skip & timer rotation, and optional account registration. 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnonymousSessionRequest
 */
export interface AnonymousSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof AnonymousSessionRequest
     */
    displayName: string;
}

/**
 * Check if a given object implements the AnonymousSessionRequest interface.
 */
export function instanceOfAnonymousSessionRequest(value: object): value is AnonymousSessionRequest {
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function AnonymousSessionRequestFromJSON(json: any): AnonymousSessionRequest {
    return AnonymousSessionRequestFromJSONTyped(json, false);
}

export function AnonymousSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnonymousSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'],
    };
}

export function AnonymousSessionRequestToJSON(json: any): AnonymousSessionRequest {
    return AnonymousSessionRequestToJSONTyped(json, false);
}

export function AnonymousSessionRequestToJSONTyped(value?: AnonymousSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'displayName': value['displayName'],
    };
}

