version: "3.9"

services:
  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app

  backend:
    image: ghcr.io/${ORG}/${REPO}-backend:${IMAGE_TAG}
    restart: always
    expose:
      - "3000"
    networks:
      - app

  frontend:
    image: ghcr.io/${ORG}/${REPO}-frontend:${IMAGE_TAG}
    restart: always
    expose:
      - "80"
    networks:
      - app

networks:
  app:
