version: "3.9"

services:
  backend:
    image: ghcr.io/${ORG}/${REPO}-api:${IMAGE_TAG}
    restart: always
    expose: [3000]
    networks: [app]

  frontend:
    image: ghcr.io/${ORG}/${REPO}-frontend:${IMAGE_TAG}
    restart: always
    ports:
      - "80:80"
    depends_on: [api]
    networks: [app]

networks:
  app:
